/*
  This file contains system parameters such as input and output pins,
  parameters, constants and data structures.
  Each parameter should have a comment on top of it explaining its use
  and preferably should be grouped together with other related parameters.
*/
#pragma once
#include <stdint.h>
#include <pins_arduino.h>

// Maximum power allowed to the motor
#define MAX_POWER 700

// PID coefficients
#define KP 2.0
#define KI 5.0
#define KD 1.0

// PWM output upper bound in microseconds
#define MAX_PWM_OUTPUT 2000

// PWM min and max range in microseconds
#define MAX_PWM 2000
#define MIN_PWM 1000

// Max allowed difference between the signals generated by each Arduino
#define TOLERANCE 100

// ADC resolution (Arduino Nano: 10-bit = 1024)
#define ADC_RES 1024

// Voltage reference for ADC
const double VREF = 5.0;  // VREF might change depending on power supply

// ADC millivolts per sample
const double mVpS = VREF / ADC_RES * 1000;   // Resolution (mV/step)

// Voltage and current sensor correction factor
const float VOLT_FACTOR = 82.924;
const float AMP_FACTOR = 27.32;

// Voltage sensor input pin
const uint8_t pinVoltage = PIN_A2;

// Current sensor input pin
const uint8_t pinCurrent = PIN_A4;

// Check pin output
const uint8_t pinCheck = 13;

// ESC PWM output pin
const uint8_t pinESC = 5;

// PWM input pins
const uint8_t pinPWMArduino = 3;
const uint8_t pinPWMRX = 2;
