#pragma once
#include <stdint.h>
#include <pins_arduino.h>

// number of PWM inputs
#define NUM_CHANNELS 2

// PWM output upper bound in microseconds
#define MAX_PWM 2000

// Max allowed difference between the signals generated by each Arduino
#define TOLERANCE 100

// ADC resolution (Arduino Nano: 10-bit = 1024)
#define ADC_RES 1024

// Voltage reference for ADC
const double VREF = 5.0;  // VREF might change depending on power supply

// ACS758 current sensor parameters
const double sens = 20;                            // Sensitivity (mV/A) from datasheet
const double resolution = VREF / ADC_RES * 1000;   // Resolution (mV/step)

// Voltage divider resistor values
const double R1 = 100000.0; // resistance of R1 (100K)
const double R2 = 10000.0;  // resistance of R2 (10K)

// Voltage divider input pin
const uint8_t pinVoltage = PIN_A2;

// ACS758 current sensor input pin
const uint8_t pinCurrent = PIN_A4;

// Check pin output
const uint8_t pinCheck = 13;

// PWM input pins
const uint8_t pinPWMArduino = 10;
const uint8_t pinPWMRX = 11;
const uint8_t PinsPWM[] = {
  pinPWMArduino,
  pinPWMRX
};

// Channel struct
typedef struct structChannels{
  uint8_t   pin;            // Channel pin
  uint8_t   pinStateLast;   // Last state the pin was in (HIGH or LOW)
  uint32_t  tStart;         // Time in microseconds the pin changed to HIGH
  uint32_t  tWidth;         // Width of the pulse in microseconds
} Channels_t;
